### ISSUE TITLE
limited terms for directed intra-layer network 

### ISSUE THREAD

**Issue by zhiyzuo** [tedhchen/multilayer.ergm#1]
First of all, thank you for this great paper and package for ERMG in the context of multiplex networks!

I am trying to use your package to model popularity and activity spread (i.e., `gwidegree` and `gwodegree` in `statnet`'s `ergm`) but do not find corresponding terms in multiplex context. Overall, I see fewer terms than those in the vanilla `ergm` package. May I ask for your advice on this please? Thank you.

**Comment by tedhchen** [comment]
Hi Zhiya. 

Thanks for your interest in the package. The included terms right now (both intra- and inter-layer) are the ones I used in the PSRM paper. I am currently adding some additional terms for my other projects, and I should be able to include the `gwidegree` and `gwodegree` terms. What is your timeline for using these terms? 

More generally, if you have specific requests, feel free to reach out here or via email, and I can let you know whether I have the bandwidth to do additional development.

**Comment by zhiyzuo** [comment]
Hi Ted, thank you for your response. I'm pretty flexible since I'm just doing some exploratory analysis. Will be excited to see more options coming out :)

**Comment by tedhchen** [comment]
Great. I will ping you here with updates. I'm tentatively planning to add at least the intra-layer gwi- and gwodegree terms sometime the first week of dec.

**Comment by tedhchen** [comment]
@zhiyzuo, sorry for the delay. I had a chance to look at this now, and realized that we can use the existing terms in the base `ergm` package to specify `gwidegree` and `gwodegree` within layers in a multilayer network.

This is how: `gwidegree(decay, fixed=T, attr='layer.mem', levels=NULL)` Keeping `levels = NULL` will give you the term on for all intra-layers. You can also keep specific layers/specify different `decay` for different layers using the term multiple times.
